- hosts: localhost
  vars:
    crypto_policies_policy: "DEFAULT:NO-SHA1"
    crypto_policies_reload: false
    tlog_scope_sssd: all
#    sshd:
#      PasswordAuthentication: yes
      
  roles:
    - role: rhel-system-roles.crypto_policies
    - role: rhel-system-roles.tlog
#    - role: rhel-system-roles.sshd
